###############################################################################
# CENTRAL DIREWOLF CONFIGURATION
###############################################################################

# Hardware Audio Configuration
ADEVICE plughw:3,0

# Channel & Modem Modulation
CHANNEL 0
MODEM 1200

# Virtual KISS Interface
SERIALKISS /dev/tnt0 19200

