#!/bin/bash

# --- PERSISTENT ROOT ENFORCEMENT ---
if [ "$EUID" -ne 0 ]; then
  echo "Please execute this network script with sudo privileges (sudo bash start.sh)."
  exit 1
fi

# Load centralized network configuration settings
if [ -f ./network.env ]; then
  source ./network.env
else
  echo "[X] Error: network.env file missing from project root folder."
  exit 1
fi

echo "=== PHASE 1: INITIALIZING VIRTUAL COM PIPELINE ==="
bash ./tty0tty/start.sh
if [ $? -ne 0 ]; then
  echo "[X] Critical error during tty0tty instantiation."
  exit 1
fi

echo "=== PHASE 2: SPAWNING DIREWOLF PACKET MODEM ==="
if [ ! -f ./direwolf/bin/direwolf ]; then
  echo "[*] Compiling direwolf inside untracked directory..."
  cd direwolf && make && cd ..
fi

# Wipe old logs to keep diagnostics clear
rm -f /var/log/direwolf_network.log

bash ./direwolf/run.sh -c ./direwolf.conf > /var/log/direwolf_network.log 2>&1 &
DIREWOLF_PID=$!
echo $DIREWOLF_PID > /tmp/direwolf_net.pid

# Verify background stabilization
sleep 2
if ! kill -0 $DIREWOLF_PID 2>/dev/null; then
  echo "[X] Critical: Direwolf closed immediately after launching!"
  echo "--- LAST ERROR LOGS ---"
  cat /var/log/direwolf_network.log
  echo "-----------------------"
  exit 1
fi
echo "[✓] Direwolf wrapper initialized background daemon (PID: $DIREWOLF_PID)"

echo "=== PHASE 3: BINDING LINUX TNC INTERFACE ==="
# Cushion time for Direwolf to successfully lock onto /dev/tnt0
sleep 1.5

# Compile tncattach from source if its binary is absent
if [ ! -f ./tncattach/tncattach ]; then
  echo "[*] tncattach binary missing. Compiling from untracked source..."
  cd tncattach && make && cd ..
fi

# Hardcode interface target cleanly to bypass dynamic loop issues
IFACE="tnc0"

# Map interfaces using your specialized tncattach wrapper execution syntax
if [ "$NETWORK_MODE" = "P2P" ]; then
  echo "Configuring Point-to-Point pipeline mapping..."
  
  # Invoke wrapper in the background explicitly to safeguard against foreground lockups
  bash ./tncattach/run.sh /dev/tnt1 115200 -d --noipv6 --noup --mtu "$P2P_MTU" > /var/log/tncattach_network.log 2>&1 &
  sleep 1.0
  
  # Bring up network link assignments using modern iproute2 suite commands
  ip addr add "$P2P_LOCAL_IP" peer "$P2P_REMOTE_IP" dev "$IFACE" 2>/dev/null || ip addr add "$P2P_LOCAL_IP" peer "$P2P_REMOTE_IP" dev tnc1
  
  # Dynamically verify which interface interface was generated by tncattach
  if ip link show tnc1 &>/dev/null; then IFACE="tnc1"; fi
  
  ip link set dev "$IFACE" up
  echo "[✓] Network routing active: $IFACE bound to point-to-point $P2P_LOCAL_IP"
else
  echo "Configuring Point-to-Multipoint broadcast pipeline mapping..."
  
  bash ./tncattach/run.sh /dev/tnt1 115200 -d -e --noipv6 --mtu "$ETH_MTU" --ipv4 "$ETH_CIDR_IP" > /var/log/tncattach_network.log 2>&1 &
  sleep 1.0
  
  if ip link show tnc1 &>/dev/null; then IFACE="tnc1"; fi
  
  ip link set dev "$IFACE" up
  echo "[✓] Network routing active: $IFACE bound to broadcast subnet $ETH_CIDR_IP"
fi

echo "=== INFRASTRUCTURE INITIALIZATION COMPLETE ==="
